name: Build Custom MicroPython

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  MPY_REPO: https://github.com/micropython/micropython.git
  BOARD: PICO_W  # Verify this matches actual directory name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            cmake \
            gcc-arm-none-eabi \
            libnewlib-arm-none-eabi \
            build-essential \
            python3 \
            python3-pip \
            git \
            wget

    - name: Clone MicroPython (with correct branch)
      run: |
        git clone --branch pico-w --recurse-submodules $MPY_REPO
        cd micropython
        git submodule update --init lib/pico-sdk lib/tinyusb

    - name: Verify board files
      run: |
        ls -l micropython/ports/rp2/boards/
        ls -l micropython/ports/rp2/boards/$BOARD/

    - name: Patch configuration
      run: |
        cd micropython/ports/rp2
        # Use proper path for board configuration
        sed -i 's/#define MICROPY_HW_USB_HID 0/#define MICROPY_HW_USB_HID 1/' boards/$BOARD/mpconfigboard.h
        sed -i 's/#define MICROPY_PY_BLUETOOTH 0/#define MICROPY_PY_BLUETOOTH 1/' mpconfigport.h
        echo "#define MICROPY_HW_USB_HID_BUFSIZE 512" >> boards/$BOARD/mpconfigboard.h

    # Rest of the steps remain the same...
