name: Build MicroPython Pico 2W Firmware

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-micropython-firmware:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout MicroPython Repository
      uses: actions/checkout@v4
      with:
        repository: micropython/micropython
        submodules: recursive
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          gcc-arm-none-eabi \
          libnewlib-arm-none-eabi \
          libstdc++-arm-none-eabi-newlib \
          python3-pip
        
        pip install pyserial
    
    - name: Prepare Pico SDK
      run: |
        git clone https://github.com/raspberrypi/pico-sdk.git
        echo "PICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk" >> $GITHUB_ENV
    
    - name: Configure Firmware Build
      working-directory: ports/rp2
      run: |
        # List available boards to verify
        ls boards/
        
        # Enable USB HID
        sed -i 's/# MICROPY_PY_USBD/MICROPY_PY_USBD/g' mpconfigport.h
        
        # Enable Bluetooth Support
        sed -i 's/# MICROPY_PY_BLUETOOTH/MICROPY_PY_BLUETOOTH/g' mpconfigport.h
        
        # Additional Bluetooth Configuration
        echo "#define MICROPY_PY_BLUETOOTH_USE_NIMBLE (1)" >> mpconfigport.h
        
        # USB HID Keyboard and Mouse
        echo "#define MICROPY_HID_KEYBOARD (1)" >> mpconfigport.h
        echo "#define MICROPY_HID_MOUSE (1)" >> mpconfigport.h
    
    - name: Build MicroPython Firmware
      working-directory: ports/rp2
      run: |
        # Correct board name
        make BOARD=RPI_PICO2_W V=1
    
    - name: Upload UF2 Firmware
      uses: actions/upload-artifact@v4
      with:
        name: rpi-pico-2w-micropython-firmware
        path: ports/rp2/build-RPI_PICO2_W/firmware.uf2
        retention-days: 30
