name: Build Custom MicroPython

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  MPY_REPO: https://github.com/micropython/micropython.git
  BOARD: PICO_W

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            cmake \
            gcc-arm-none-eabi \
            libnewlib-arm-none-eabi \
            build-essential \
            python3 \
            python3-pip \
            git \
            wget

    - name: Clone MicroPython
      run: |
        git clone --recurse-submodules $MPY_REPO
        cd micropython
        git submodule update --init lib/pico-sdk lib/tinyusb

    - name: Patch configuration
      run: |
        cd micropython/ports/rp2
        # Enable USB HID
        sed -i 's/#define MICROPY_HW_USB_HID 0/#define MICROPY_HW_USB_HID 1/' boards/$BOARD/mpconfigboard.h
        # Enable Bluetooth
        sed -i 's/#define MICROPY_PY_BLUETOOTH 0/#define MICROPY_PY_BLUETOOTH 1/' mpconfigport.h
        # Increase HID buffer size
        echo "#define MICROPY_HW_USB_HID_BUFSIZE 512" >> boards/$BOARD/mpconfigboard.h

    - name: Build mpy-cross
      run: |
        cd micropython/mpy-cross
        make

    - name: Build port
      run: |
        cd micropython/ports/rp2
        make BOARD=$BOARD clean
        make BOARD=$BOARD

    - name: Upload UF2 Artifact
      uses: actions/upload-artifact@v4
      with:
        name: micropython-pico2w.uf2
        path: micropython/ports/rp2/build-$BOARD/firmware.uf2
