name: Build MicroPython for Pico W with USBDevice

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout MicroPython
      uses: actions/checkout@v4
      with:
        repository: micropython/micropython
        path: micropython

    - name: Initialize Submodules
      run: |
        cd micropython
        git submodule update --init --recursive

    - name: Enable USBDevice in mpconfigport.mk
      run: |
        cd micropython/ports/rp2
        # Append the config line if not already present
        grep -q '^MICROPY_PY_MACHINE_USBDEVICE = 1' mpconfigport.mk || echo 'MICROPY_PY_MACHINE_USBDEVICE = 1' >> mpconfigport.mk

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential python3 python3-pip

    - name: Build MicroPython for Pico W
      run: |
        cd micropython
        make submodules
        make -j$(nproc) PICO_BOARD=PICO_W

    - name: Upload firmware.uf2 artifact
      uses: actions/upload-artifact@v4
      with:
        name: pico_w_usbdevice_firmware
        path: micropython/build-PICO_W/firmware.uf2
